### ISSUE TITLE
Is this the official repository?

### ISSUE THREAD

**Issue by kainjow** [asgeir/qglitter#1]
Previously a few years back I had submitted changes in the [Bitbucket](https://bitbucket.org/asgeir/qglitter) repository. Should I add pull requests to GitHub now? (I'd prefer, but I can do either.) There are some changes I'd like to contribute. For example, the .ui files need to be moved to work with CMake's [AUTOUIC](https://cmake.org/cmake/help/v3.1/prop_tgt/AUTOUIC.html) feature.

**Comment by asgeir** [comment]
I've stopped using bitbucket so this is where I'm keeping the code now

**Comment by kainjow** [comment]
OK sounds good. Maybe the Bitbucket repo should link to this one somehow?

**Comment by asgeir** [comment]
I added a note to the readme
